* 第一节 [2019年10月17日18:17:43]
** 笔记:
下面所提到的`C`例如`C-x`的意思是指`Control key`
下面所提到的`M`例如`M-x`的意思是指`Alt key`

`C-g`退出或取消当前已键入的命令。
** 步骤
例如: `C-x C-s`用于保存当前缓冲区/文件。如果我键入`C-x`但我改变了注意，我可以键入`C-g`取消这个命令。

1. 第一部分: 移动光标
   1) 向上移动一行: C-p
   2) 向下移动一行: C-n
   3) 向前移动一个字符: C-f
   4) 向后移动一个字符: C-b
   5) 向前移动一个单词: M-f
   6) 向后移动一个单词: M-b
   7) 移动到当前行的行首: C-a
   8) 移动到当前行的行尾: C-e
   9) 删除当前光标至行尾字符: C-k
   10) 删除后一个单词: M-DEL
   11) 删除前一个字符: C-d
   12) 删除前一个单词: M-d
   13) 单词转为大写: M-u
   14) 单词转为小写: M-l
   15) 单词首字母大写: M-c
   16) 单词之间调换位置: M-t
   17) 字符之间调换位置: C-t
2. 第二部分: 保存、打开、查找文件、缓冲区
   1) 写入当前缓冲区至一个文件: C-x C-w 然后输入文件路径和名字。我将当前缓冲区写入至~/Desktop/LearnEmacs/Section-01.org
   2) 保存文件: C-x C-s
   3) 关闭当前缓冲区: C-x k
   4) 查找或打开文件: C-x C-f

* 第二节 [2019年10月17日18:21:16]
** 步骤
这一节，我将要介绍如何添加ELPA仓库并且安装一个Emacs主题。

1. 配置ELPA仓库。
   1) 创建一个Emacs初始化文件: ~/.emacs.d/init.el。
   2) 打开: https://elpa.emacs-china.org/ 并且复制代码段到init.el。
   3) 检查`init.el`这个缓冲区: M-x eval-buffer
2. 安装一个Emacs主题包
   1) 键入`M-x list-packages` 以列出所有Eamcs包。
   2) 选择一个主题包然后输入`i`将其选中。
   3) 输入`x`开始安装包。
   4) 在你的`init.el`中加载主题。
   5) 键入`M-x eval-buffer`以重载`init.el`文件

现在，你会看到一个更好看的Emacs。 :P
* 第三节 [2019年10月17日18:55:41]
** 步骤
这一节，我将会介绍如何隐藏工具栏和菜单栏。

我们使用了两个函数: tool-bar-mode 和 menu-bar-mode.

如何退出Emacs呢? 快捷键是: `C-x C-c`

如何新建一个窗格呢?

1. 新建水平窗格: `C-x 2`
2. 新建垂直窗格: `C-x 3`
3. 选择窗格: `C-x o` (`o` 意思是 `other`)
4. 关闭除当前窗口以外的窗口: `C-x 1`

如何跳转至当前缓冲区的开头? `M-<`

如何跳转至当前缓冲区的结尾? `M
* 第四节 [2019年10月17日19:08:35]
这一节，我将会介绍如何安装一些包，正也是我喜欢的。

1. use-package: 安装和管理其他包。
2. magit: 在Emacs中使用Git
3. lispy: 写Lisp的模式

现在我将使用magit创建一个仓库并且新建一个提交。

使用lispy，我们能够平滑的在Lisp Mode跳转。
* 第五节 [2019年10月17日20:24:04]
今天，我将会介绍如何设置Emacs字体以及使用Magit插件。

1. 设置字体使用 `default-framke-alist`变量
2. 使用magit
   1) 为当前仓库添加一个远程仓库。
   2) 我们使用`git@github.com:evanmeek/EmacsNote.git`用于你的远程仓库。
   3) 从origin拉取提交并且将本地提交推送至远程仓库。
      - 我们有一个未暂存更改，我们现在将其暂存。
* 第六节 [2019年10月17日23:55:59]
这一节，我将会介绍如何在一个组织内使用magit.

1. 创建一个新的仓库。
* 第十六节 [2019年10月18日09:18:46]
这一节，我将会介绍如何在Emacs中使用org-mode。

当前文件就是一个Org文件,org-mode是开启的。

1. `M-x org-mode`开启org-mode。
2. `M-Enter`新建相同级别的标题。
3. `S-right/left` 切换  当前项为`TODO`，`DONE`或默认。
4. `M-right/left` 改变当前项等级。
5. `M-S-Enter`创建一个TODO项。
6. `S-right`循环切换不同样式的顺序/序号列表。
7. `C-c C-p`移动至上一项。
8. `C-c C-n`移动至下一项。
9. `C-c C-b`移动至后一同级项。
10. `C-c C-f`移动至前一同级项。
11. `C-c C-u`移动至父项。
12. `C-u C-c !`插入时间日历。
13. `C-c C-x C-i`开始计时。
14. `C-c C-x C-o`关闭计时。
